name: Pylint

on: 
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Bootstrap
      run: |
         ./bootstrap.sh
 
    - name: Analysing the code with pylint
      run: |
        sudo pip3 install pylint
        pylint `ls -R|grep .py$|xargs`
    
    
          
    - name: Test pytest 
      run: |
        sudo pip3 install pytest
        pytest

        
        
    